name: worldofgoals
description: A gamified goal tracking application
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # UI
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.1
  
  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  
  # Routing
  go_router: ^13.0.0
  
  # Database
  drift: ^2.14.1
  sqlite3_flutter_libs: ^0.5.28
  path_provider: ^2.1.1
  path: ^1.8.3
  
  # Network
  dio: ^5.4.0
  
  # Storage
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  encrypted_shared_preferences: ^3.0.1
  
  # Utils
  intl: ^0.19.0
  logger: ^2.0.2+1
  uuid: ^4.2.2
  bcrypt: ^1.1.3
  
  # Code Generation
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Linting
  flutter_lints: ^3.0.1
  
  # Code Generation
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  freezed: ^2.4.6
  drift_dev: ^2.14.1
  
  # Testing
  mockito: ^5.4.4

flutter:
  uses-material-design: true
  assets:
    # - assets/images/
    # - assets/icons/
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
